spring.datasource:
  url: jdbc:mysql://localhost:3306/grocery_family?createDatabaseIfNotExist=true
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
  # In this mode Hibernate will update the database schema by comparing
  # the existing schema with the entity mappings and generate the appropriate
  # schema migration scripts
  hibernate.ddl-auto: update
  # Log Hibernate/JPA SQL queries
  show-sql: true