spring.datasource:
  url: jdbc:mysql://localhost:3306/finalproject
  driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa.properties:
  hibernate.dialect: org.hibernate.dialect.MySQLDialect
  # In this mode Hibernate will update the database schema by comparing
  # the existing schema with the entity mappings and generate the appropriate
  # schema migration scripts
  hibernate.ddl-auto: update

# Log Hibernate/JPA SQL queries
spring.jpa.show-sql: true