spring.datasource:
  url: jdbc:h2:mem:grocery_family;LOCK_TIMEOUT=10000
  driver-class-name: org.h2.Driver

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate.ddl-auto: update
  show-sql: false