spring.profiles.active: @spring.profiles.active@

GroceryDad:
  scrapers:
    - source: BARBORA
      uri: https://barbora.ee
      cache:
        directory: cache/barbora
      categories:
        - [ "Dairy and eggs", "Milk", "Pasteurised milk" ]
    - source: PRISMA
      uri: https://prismamarket.ee
      cache:
        directory: cache/prisma
      categories:
        - [ "Groceries", "Pets", "Toys for pets" ]
    - source: RIMI
      uri: https://rimi.ee/epood/en
      cache:
        directory: cache/rimi
      categories:
        - [ "Groceries", "All category products" ]