GroceryDad:
  api.uri: http://localhost:8080

  enabled:
#    - barbora
#    - prisma
    - rimi

  scrapers:
    barbora:
      namespace: barbora.ee
      uri: https://barbora.ee
      cache:
        directory: cache/barbora
      categories:
        - [ "Dairy and eggs", "Yoghurts and desserts", "Flavored yoghurts" ]
#        - [ "Vegetables and fruits", "Fruits and berries", "Bananas" ]
        - [ "Household and pets", "Pets", "Dry dog food" ]
#        - [ "Dairy and eggs", "Milk", "Pasteurised milk" ]
      timeout: 30s
      sleepDelay: 500ms

    prisma:
      namespace: prismamarket.ee
      uri: https://prismamarket.ee
      cache:
        directory: cache/prisma
      categories:
        - [ "Groceries", "Fruits and vegetables", "Fruit" ]
        - [ "Groceries", "Pets", "Dog food" ]
      timeout: 10s
      sleepDelay: 100ms

    rimi:
      namespace: rimi.ee
      uri: https://rimi.ee/epood/en
      cache:
        directory: cache/rimi
      categories:
        - [ "Pre-order festivity meals", "Pre-order appetizers and selection plates" ]
#        - [ "Fruits, vegetables, flowers", "Fruits", "Bananas" ]
#        - [ "Pet goods", "Dog food", "Dry food for dogs" ]
#        - [ "Groceries", "Canned products", "Mushrooms" ]
#        - [ "Bread, pastry, confectionery", "Rimi bakeries" ]
      timeout: 10s
      sleepDelay: 100ms