GroceryDad:
  api.uri: http://localhost:8080

  enabled:
#    - barbora
#    - prisma
    - rimi

  scrapers:
    barbora:
      namespace: barbora.ee
      url: https://barbora.ee
      cache:
        directory: cache/barbora
      categories:
        - [ "Vegetables and fruits", "Fruits and berries", "Bananas", "*" ]
        - [ "Household and pets", "Pets", "Dry dog food", "*" ]
        - [ "Dairy and eggs", "Yoghurts and desserts", "Flavored yoghurts", "*" ] # two product pages
      timeout: 5s
      sleepDelay: 500ms

    prisma:
      namespace: prismamarket.ee
      url: https://prismamarket.ee
      cache:
        directory: cache/prisma
      categories:
        - [ "Groceries", "Fruits and vegetables", "Fruit", "*" ] # need to scroll down
        - [ "Groceries", "Pets", "Dog food", "*" ]
      timeout: 5s
      sleepDelay: 100ms

    rimi:
      namespace: rimi.ee
      url: https://rimi.ee/epood/en
      cache:
        directory: cache/rimi
      categories:
        - [ "Fruits, vegetables, flowers", "Fruits", "Bananas", "*" ]
        - [ "Pet goods", "Dog food", "Dry food for dogs", "*" ]
        - [ "Pre-order festivity meals", "Pre-order appetizers and selection plates", "*" ] # two pages
      timeout: 5s
      sleepDelay: 100ms